kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-siad-mahara-dev-01-vol01
  namespace: siad-mahara-dev-01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi