---
# Source: mcrouter/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mah-mcrouter
  namespace: siad-mahara-dev-01
  labels:
    app: mcrouter
    chart: mcrouter-0.1.1
    release: mah
    heritage: Tiller
data:
  config.json: |-
    {
      "pools": {
        "A": {
          "servers": [
            "mah-memcached-0.mah-memcached.siad-mahara-dev-01:11211",
            "mah-memcached-1.mah-memcached.siad-mahara-dev-01:11211",
            "mah-memcached-2.mah-memcached.siad-mahara-dev-01:11211",
          ]
        }
      },
      "route": "PoolRoute|A"
    }
---
# Source: mcrouter/charts/memcached/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mah-memcached
  namespace: siad-mahara-dev-01
  labels:
    app: mah-memcached
    chart: "memcached-1.2.1"
    release: "mah"
    heritage: "Tiller"
spec:
  clusterIP: None
  ports:
  - name: memcache
    port: 11211
    targetPort: memcache
  selector:
    app: mah-memcached

---
# Source: mcrouter/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mah-mcrouter
  namespace: siad-mahara-dev-01
  labels:
    app: mah-mcrouter
    chart: "mcrouter-0.1.1"
    release: "mah"
    heritage: "Tiller"
spec:
  clusterIP: None
  ports:
  - name: mcrouter-port
    port: 5000
    targetPort: mcrouter-port
  selector:
    app: mah-mcrouter

---
# Source: mcrouter/charts/memcached/templates/statefulset.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mah-memcached
  namespace: siad-mahara-dev-01
  labels:
    app: mah-memcached
    chart: "memcached-1.2.1"
    release: "mah"
    heritage: "Tiller"
spec:
  serviceName: mah-memcached
  replicas: 3
  template:
    metadata:
      labels:
        app: mah-memcached
        chart: "memcached-1.2.1"
        release: "mah"
        heritage: "Tiller"
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - topologyKey: "kubernetes.io/hostname"
      #       labelSelector:
      #         matchLabels:
      #           app:  mah-memcached
      #           release: "mah"
      containers:
      - name: mah-memcached
        image: memcached:1.4.36-alpine
        imagePullPolicy: ""
        command:
        - memcached
        - -m 64
        - -o
        - modern
        - -v
        ports:
        - name: memcache
          containerPort: 11211
        livenessProbe:
          tcpSocket:
            port: memcache
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: memcache
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          

---
# Source: mcrouter/templates/statefulset.yaml

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mah-mcrouter
  namespace: siad-mahara-dev-01
  labels:
    app: mah-mcrouter
    chart: "mcrouter-0.1.1"
    release: "mah"
    heritage: "Tiller"
  annotations:
    checksum/config: caf7678e6cf91f2713ff0078e9412d1d0f05755dfbedc097a5d30dda54963579
spec:
  serviceName: mah-mcrouter
  replicas: 1
  template:
    metadata:
      labels:
        app: mah-mcrouter
        chart: "mcrouter-0.1.1"
        release: "mah"
        heritage: "Tiller"
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - topologyKey: "kubernetes.io/hostname"
      #       labelSelector:
      #         matchLabels:
      #           app:  mah-mcrouter
      #           release: "mah"
      containers:
      - name: mah-mcrouter
        image: jphalip/mcrouter:0.36.0
        imagePullPolicy: ""
        command: ["mcrouter"]
        args:
        - -p 5000
        - --config-file=/etc/mcrouter/config.json
        volumeMounts:
        - name: config
          mountPath: /etc/mcrouter
        ports:
        - name: mcrouter-port
          containerPort: 5000
        livenessProbe:
          tcpSocket:
            port: mcrouter-port
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: mcrouter-port
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 256m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
          
      volumes:
      - name: config
        configMap:
          name: mah-mcrouter

---
# Source: mcrouter/templates/daemonset.yaml

